import {Customer,Intervention,Outcome,AuditLog} from '../models/index.js'; import {revenueAtRisk,explain,strategies} from '../services/risk.js'; import {predict} from '../services/ml.js';
export async function dashboard(req,res){const cs=await Customer.find(); const risk=cs.reduce((a,c)=>a+(c.churnProbability||0),0); const arr=cs.map(c=>revenueAtRisk(c)); res.json({kpis:{customers:cs.length,atRisk:arr.reduce((a,b)=>a+b,0),highRisk:cs.filter(c=>['HIGH','CRITICAL'].includes(c.riskLevel)).length,avgChurn:cs.length?risk/cs.length:0},riskDistribution:['LOW','MEDIUM','HIGH','CRITICAL'].map(level=>({level,count:cs.filter(c=>c.riskLevel===level).length})),customers:cs.slice(0,8)});}
export async function customers(req,res){const q=req.query.q||''; const filter=q?{name:{$regex:q,$options:'i'}}:{}; res.json(await Customer.find(filter).sort({churnProbability:-1}));}
export async function customer(req,res){const c=await Customer.findById(req.params.id); if(!c)return res.status(404).json({error:'Customer not found'}); res.json({...c.toObject(),revenueAtRisk:revenueAtRisk(c),signals:explain(c)});}
export async function score(req,res){const c=await Customer.findById(req.params.id); if(!c)return res.status(404).json({error:'Customer not found'}); const p=await predict(c); c.churnProbability=p.churn_probability;c.riskLevel=p.risk_level; await c.save(); await AuditLog.create({actor:req.user?.email||'system',action:'SCORE_CUSTOMER',entityType:'Customer',entityId:c.id,metadata:p}); res.json(p);}
export async function interventions(req,res){const list=await Intervention.find().populate('customer').sort({createdAt:-1}); res.json(list);}
export async function recommend(req,res){const c=await Customer.findById(req.params.id); if(!c)return res.status(404).json({error:'Customer not found'}); const rows=strategies(c).filter(x=>x.netValue>0).sort((a,b)=>b.netValue-a.netValue); const created=await Intervention.insertMany(rows.map(x=>({...x,customer:c._id,reason:explain(c).join(', ')}))); res.json(created);}
export async function simulator(req,res){const c=await Customer.findById(req.params.id); if(!c)return res.status(404).json({error:'Customer not found'}); const cost=Number(req.body.cost||0),retention=Number(req.body.retention||0); res.json({cost,retention,expectedRevenue:c.monthlyRevenue*12*retention,netValue:c.monthlyRevenue*12*retention-cost});}
export async function outcomes(req,res){res.json(await Outcome.find().populate('customer intervention').sort({createdAt:-1}));}
export async function analytics(req,res){const cs=await Customer.find(); res.json({revenueAtRisk:cs.reduce((s,c)=>s+revenueAtRisk(c),0),byPlan:['basic','standard','premium'].map(plan=>({plan,count:cs.filter(c=>c.planType===plan).length,atRisk:cs.filter(c=>c.planType===plan).reduce((s,c)=>s+revenueAtRisk(c),0)}))});}
export async function audit(req,res){res.json(await AuditLog.find().sort({createdAt:-1}).limit(200));}
